-- REMINDRA v1 cloud schema for Supabase Postgres.
-- Run this SQL in Supabase SQL Editor before deploying to Vercel.

create table if not exists public.hotline_orders (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  dealer_po_number text not null default '',
  po_date date not null,
  customer_name text not null,
  phone_number text not null default '',
  part_number text not null default '',
  part_name text not null default '',
  eta_revision date,
  eta_earliest date,
  eta_latest date,
  portal_status text not null default '',
  progress_percent text not null default '',
  order_qty integer not null default 0,
  engine_number text not null default '',
  frame_number text not null default '',
  plate_number text not null default '',
  vehicle_type text not null default '',
  price integer not null default 0,
  status text not null default 'Booked',
  follow_up_status text not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.mechanic_recommendations (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  customer_name text not null,
  phone_number text not null default '',
  vehicle_info text not null default '',
  component text not null,
  recommendation text not null,
  follow_up_date date not null,
  estimated_value integer not null default 0,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.reminder_tasks (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  source_type text not null,
  source_id bigint not null,
  customer_name text not null,
  phone_number text not null default '',
  message text not null,
  due_date date not null,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, source_type, source_id)
);

create table if not exists public.message_templates (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  type text not null,
  name text not null,
  body text not null,
  updated_at timestamptz not null default now(),
  unique (user_id, type)
);

create table if not exists public.whatsapp_message_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  reminder_id bigint references public.reminder_tasks(id) on delete set null,
  source_type text not null,
  source_id bigint not null,
  phone_number text not null default '',
  message text not null default '',
  wa_message_id text not null default '',
  delivery_status text not null default 'draft',
  error_message text not null default '',
  sent_at timestamptz,
  delivered_at timestamptz,
  read_at timestamptz,
  failed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.hotline_orders enable row level security;
alter table public.mechanic_recommendations enable row level security;
alter table public.reminder_tasks enable row level security;
alter table public.message_templates enable row level security;
alter table public.whatsapp_message_logs enable row level security;

create policy "hotline_orders_select_own" on public.hotline_orders for select using (auth.uid() = user_id);
create policy "hotline_orders_insert_own" on public.hotline_orders for insert with check (auth.uid() = user_id);
create policy "hotline_orders_update_own" on public.hotline_orders for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "hotline_orders_delete_own" on public.hotline_orders for delete using (auth.uid() = user_id);

create policy "mechanic_recommendations_select_own" on public.mechanic_recommendations for select using (auth.uid() = user_id);
create policy "mechanic_recommendations_insert_own" on public.mechanic_recommendations for insert with check (auth.uid() = user_id);
create policy "mechanic_recommendations_update_own" on public.mechanic_recommendations for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "mechanic_recommendations_delete_own" on public.mechanic_recommendations for delete using (auth.uid() = user_id);

create policy "reminder_tasks_select_own" on public.reminder_tasks for select using (auth.uid() = user_id);
create policy "reminder_tasks_insert_own" on public.reminder_tasks for insert with check (auth.uid() = user_id);
create policy "reminder_tasks_update_own" on public.reminder_tasks for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "reminder_tasks_delete_own" on public.reminder_tasks for delete using (auth.uid() = user_id);

create policy "message_templates_select_own" on public.message_templates for select using (auth.uid() = user_id);
create policy "message_templates_insert_own" on public.message_templates for insert with check (auth.uid() = user_id);
create policy "message_templates_update_own" on public.message_templates for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "message_templates_delete_own" on public.message_templates for delete using (auth.uid() = user_id);

create policy "whatsapp_message_logs_select_own" on public.whatsapp_message_logs for select using (auth.uid() = user_id);
create policy "whatsapp_message_logs_insert_own" on public.whatsapp_message_logs for insert with check (auth.uid() = user_id);
create policy "whatsapp_message_logs_update_own" on public.whatsapp_message_logs for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "whatsapp_message_logs_delete_own" on public.whatsapp_message_logs for delete using (auth.uid() = user_id);

create index if not exists hotline_orders_user_po_date_idx on public.hotline_orders(user_id, po_date);
create index if not exists reminder_tasks_user_due_date_idx on public.reminder_tasks(user_id, due_date);
create index if not exists mechanic_recommendations_user_follow_up_idx on public.mechanic_recommendations(user_id, follow_up_date);
create index if not exists whatsapp_message_logs_user_reminder_idx on public.whatsapp_message_logs(user_id, reminder_id);
create index if not exists whatsapp_message_logs_wa_message_id_idx on public.whatsapp_message_logs(wa_message_id);
