-- REMINDRA WhatsApp automation migration.
-- Run this in Supabase SQL Editor if the base REMINDRA tables already exist.

create table if not exists public.whatsapp_message_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  reminder_id bigint references public.reminder_tasks(id) on delete set null,
  source_type text not null,
  source_id bigint not null,
  phone_number text not null default '',
  message text not null default '',
  wa_message_id text not null default '',
  delivery_status text not null default 'draft',
  error_message text not null default '',
  sent_at timestamptz,
  delivered_at timestamptz,
  read_at timestamptz,
  failed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.whatsapp_message_logs enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'whatsapp_message_logs' and policyname = 'whatsapp_message_logs_select_own') then
    create policy "whatsapp_message_logs_select_own" on public.whatsapp_message_logs for select using (auth.uid() = user_id);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'whatsapp_message_logs' and policyname = 'whatsapp_message_logs_insert_own') then
    create policy "whatsapp_message_logs_insert_own" on public.whatsapp_message_logs for insert with check (auth.uid() = user_id);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'whatsapp_message_logs' and policyname = 'whatsapp_message_logs_update_own') then
    create policy "whatsapp_message_logs_update_own" on public.whatsapp_message_logs for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'whatsapp_message_logs' and policyname = 'whatsapp_message_logs_delete_own') then
    create policy "whatsapp_message_logs_delete_own" on public.whatsapp_message_logs for delete using (auth.uid() = user_id);
  end if;
end $$;

create index if not exists whatsapp_message_logs_user_reminder_idx on public.whatsapp_message_logs(user_id, reminder_id);
create index if not exists whatsapp_message_logs_wa_message_id_idx on public.whatsapp_message_logs(wa_message_id);
